// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-2',
    aws_cognito_identity_pool_id: 'us-east-2:4f0613bd-5537-4bc6-be78-1200e937fc47',
    aws_cognito_region: 'us-east-2',
    aws_user_pools_id: 'us-east-2_KDk18FZjg',
    aws_user_pools_web_client_id: '6159tt9ts8hf0piv33p6bu3shs',
    oauth: {},
  };
  
  
  export default awsmobile;